### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Thekeshawn78** [azclub-ltd/Termux-JohnTheRipper-Installer#4]
![Screenshot_2024-08-06-19-47-01-233_com termux](https://github.com/user-attachments/assets/c422f994-294c-4085-9259-86fe31ad6915)

How to fix this

**Comment by Thekeshawn78** [comment]
@shahriarkabir-sagor hello?

**Comment by KabirHere** [comment]
The installer might not be causing that problem. please try to reinstall. You can message me on [Telegram](https://t.me/whoami21k). Also This repository is no longer maintained.
